import turtle as t
t.shape("turtle")
t.write(t.position())
t.forward(100)
t.write(t.position())
t.left(90)
t.forward(100)
t.write(t.position())
t.write(t.position())
t.forward(100)
t.write(t.position())
t.left(90)
t.forward(100)
t.write(t.position())
import turtle as t
t.shape("turtle")
t.write(t.position())
t.forward(100)
t.write(t.position())
t.left(90)
t.forward(100)
t.write(t.position())
import turtle as t
t.shape("turtle")
t.write(t.position())
t.forward(100)
t.write(t.position())
t.left(90)
t.forward(100)
t.write(t.position())
